version: '3.4'

services:
  app:
    build: .
    image: deploy_app
    restart: always
    networks:
      - nginx
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: analytics.legiec.info
      LETSENCRYPT_HOST: analytics.legiec.info

networks:
  nginx:
    external: true
