version: '3.4'

services:
  app:
    build: .
    image: deploy_app
    restart: always
    networks:
      - nginx
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: demo.example.com
      LETSENCRYPT_HOST: demo.example.com

networks:
  nginx:
    external: true
